### ISSUE TITLE
filter.yaml with custom msg and service

### ISSUE THREAD

**Issue by hesham1salem** [husarnet/dds-router#19]
I ask about how I can add  custom msg and service to filter.yaml 
for example some thing similar  to :
```yaml
allowlist:
  - name: "rt/mytopic"
    type: "mycustom_msg"
blocklist: []
builtin-topics: []

```
and how to allow all topics
